### ISSUE TITLE
Possible memory leak in TAllergies

### ISSUE THREAD

**Issue by PKGeorgiev** [exercism/xdelphi#115]
TAllergies creates a TList and a TDictionary, but does not release them. This is usually done in the constructor (which is not defined).

**Comment by rpottsoh** [comment]
@PKGeorgiev thanks for taking the time to review my example solution for the exercise `Allergies`.  You have pointed a couple of things that I can improve.

* The `TList` that you mention is actually never used and is never instantiated so I will remove its declaration from `TAllergies`.
* I will add a `destructor` that will clean up the instance of `TDictionary` that is created within the constructor.

**Comment by rpottsoh** [comment]
@PKGeorgiev take a moment to look over my [changes](https://github.com/exercism/xdelphi/pull/116).  I'll allow my PR to sit for a couple of days before I merge it.  Let me know if you have any questions and thanks again for your input.
