### ISSUE TITLE
Which Pascal?

### ISSUE THREAD

**Issue by catb0t** [exercism/xdelphi#23]
There's Delphi (Borland Pascal), Lazarus (Free Pascal), GNU Pascal, Turbo Pascal, UCSD Pascal, Object Pascal, the list goes on and on. It would be nice to know which implementation is used, and talk about how to get it in INSTALLATION.md.

Also, I can't make an icon until I know which distribution this is using, because I can't read Pascal and so I don't know what kind the current code in the PRs is.

**Comment by rpottsoh** [comment]
I have been using Delphi XE5 (Embarcadero) with DUnitX as my test framework.  DUnitX is compatible with Delphi 2010 through the most recent release of Delphi.

I only have a passing familiarity with FPC/Lazarus.  I don't know that DUnitX would be fully compatible. 

Sent from my android device.

-----Original Message-----

**Comment by rpottsoh** [comment]
Icon has been created and merged to master.  Also issue #45 is discussing renaming track to Delphi Pascal and perhaps creating a "Sister" Object Pascal track that would be suited for Free Pascal/Lazarus.

**Comment by kotp** [comment]
Closing as I think the Icon has been chosen to be Blaise Pascal.
