### ISSUE TITLE
Rename track from Pascal to Delphi

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xdelphi#71]
This track is implemented in the Delphi dialect, and to keep things unambiguous (and legal), we should rename the track to Delphi.

TRACK ID: `delphi`
LANGUAGE: `Delphi Pascal`

See the discussion in #45 for details.

- [x] Rename repository (can be done even without other changes, since GitHub redirects)
- [x] Update README
- [x] Update references in `config.json`
- [x] Update references in `docs/*.md` files
- [x] Remove xpascal submodule from Trackler
- [x] Add xdelphi as submodule to Trackler
- [x] Deploy
- [x] Update track mentors (kotp, rpottsoh)
- [x] Update exercises, iterations in database

**Comment by kotp** [comment]
I would say that the removal xpascal submodule from Tracker is premature, as we should have it for the Pascal track.  This will involve some of the resources that are mentioned in the current documents, specifically, I think, freepascal references.  Though hopefully generic enough for Pascal in general.

**Comment by kytrinyx** [comment]
> I would say that the removal xpascal submodule from Tracker is premature, as we should have it for the Pascal track.

It's a one-line command to add it when we get a pascal track. I felt it was cleaner to remove it for now. It probably doesn't matter either way, to be honest, as long as stuff doesn't break (and I think it won't).

**Comment by kotp** [comment]
It redirects well for now... so no immediate action necessary in regards.  So it is a good clean change.

**Comment by kotp** [comment]
Should I add this as a TODO in that repository?  It is something that I think @rpottsoh and I were thinking of doing.

**Comment by kytrinyx** [comment]
When you decide you want to do it, let me know and I'll bootstrap the repository for you.

**Comment by kotp** [comment]
Might get the "Good to go" later this evening.
