### ISSUE TITLE
AppVeyor failing and Travis CI passing PR checks.

### ISSUE THREAD

**Issue by rpottsoh** [exercism/xdelphi#87]
AppVeyor has recently been added.  It appears it is failing to check PRs that Travis CI is passing.  See PR #86 .

**Comment by kotp** [comment]
That is likely just configuration.  They should really  not interfere with each other, unless they use the same filenames.... that would be surprising.

**Comment by rpottsoh** [comment]
I agree.  I wouldn't suspect one to be affected by the other.

**Comment by rpottsoh** [comment]
I don't think this issue has any relevance.  It isn't trying to solve anything.  Continuous integration is already an issue covered [here](https://github.com/exercism/xdelphi/issues/3).
