### ISSUE TITLE
hello-world: Shouldn't this exercise supply the solution

### ISSUE THREAD

**Issue by rpottsoh** [exercism/xdelphi#99]
@kotp at this time the solution to hello-world is not supplied to the student.  I'm thinking it should since the point of the exercise is simply to test that the tools for this track are running correctly.  Ruby and C# are not supplying the solution near as I can tell.  

Perhaps this issue should be in x-common?

**Comment by kotp** [comment]
It should be an exercise of how to solve it, though it should be trivial.  If a comment is placed there to specifically guide and inform, I don't really see harm in that.

**Comment by rpottsoh** [comment]
I'll review the test runner and see how I might alter the comment at the top of the file.  The solution file is very short so I may end up with that code inserted at the top, commented, with instructions that this code should be placed in a new file named......

**Comment by kotp** [comment]
Closing due to #100
